using System.Collections;
using UnityEngine;
using UnityEngine.UI;

public class LoadPanel : MonoBehaviour
{
    private Image panelImage;

    private void Awake()
    {
        panelImage = GetComponent<Image>();
    }
    private void OnEnable()
    {
        StartCoroutine(ChangeColor());
    }

    /// <summary>
    /// ม๘ยฅ ทฮต๙ภฬ วสฟไวา ถง, ณหณหวั ฝรฐฃภป ฟฉฑโ มใพ๎มึฐํ, ภฬ ฝรฐฃภฬ ม๖ณชธ้ พภภป บธฟฉมึฑโ.
    /// </summary>
    /// <returns></returns>
    private IEnumerator ChangeColor()
    {
        float loadTime = 0.55f;
        float elapsedTime = 0;
        Color baseColor = panelImage.color; // ฐหมคป๖

        while (elapsedTime < loadTime)
        {
            elapsedTime += Time.deltaTime;
            float alphaValue = Mathf.Lerp(0f, 1f, elapsedTime / loadTime);
            panelImage.color = new Color(baseColor.r, baseColor.g, baseColor.b, alphaValue);

            yield return null;
        }

        panelImage.color = new Color(baseColor.r, baseColor.g, baseColor.b, 1);

        gameObject.SetActive(false);
    }
}
