using TMPro;
using UnityEngine;

public enum KeyType
{
    Attack = 0, Jump = 1, Dash = 2, Up = 3, Down = 4, Left = 5, Right = 6,
    Throw = 7, Interaction = 8, KeyCount = 9
};
public class InputSetting : MonoBehaviour
{
    [SerializeField]
    private TextMeshProUGUI[] changeKeyName;
    [SerializeField]
    private KeyBindingData keyBindingData;
    private bool[] isClickKeyChanger = new bool[(int)KeyType.KeyCount];

    private void Awake()
    {
        for (int i = 0; i < isClickKeyChanger.Length; i++)
        {
            isClickKeyChanger[i] = false;
        }
    }

    private void OnEnable()
    {
        Time.timeScale = 0;
        for (int i = 0; i < changeKeyName.Length; i++)
        {
            changeKeyName[i].text = keyBindingData.keys[i].ToString();
        }
    }
    private void OnGUI()
    {
        Event currentEvent = Event.current;
        if (currentEvent.keyCode == KeyCode.Escape) return;

        for (int i = 0; i < isClickKeyChanger.Length; i++) // ลฐ บฏฐๆภฬ ศฐผบศญ ตวพ๎ภึภป ฝร
        {
            if (isClickKeyChanger[i])
            {
                if (currentEvent.type == EventType.KeyDown)
                {
                    ChangeKeyInput(i, currentEvent.keyCode); // บฏฐๆวา ลฐฟอ ว๖ภ็ ดฉธฅ KeyCode ธฆ ภฮภฺทฮ บธณฟ 
                }
                else if (currentEvent.type == EventType.MouseDown)
                {
                    KeyCode mouseKeyCode = KeyCode.None;
                    switch (currentEvent.button)
                    {
                        case 0: mouseKeyCode = KeyCode.Mouse0; break;
                        case 1: mouseKeyCode = KeyCode.Mouse1; break;
                    }
                    ChangeKeyInput(i, mouseKeyCode);
                }
            }
        }
    }

    private void Update()
    {
        if (Input.GetKeyUp(KeyCode.Escape))
        {
            ExitInputSetting();
        }
    }

    public void ExitInputSetting()
    {
        UIManager.Instance.OnPausePanel();
        this.gameObject.SetActive(false);
    }
    private void ChangeKeyInput(int keyType, KeyCode pressedKeyCode) // บฏฐๆ ลฐฐก ดญธฑ ฝร , วุด็ ลฐ text บฏฐๆ นื ลฐ บฏฐๆ วิผ๖ ศฃรโ
    {
        if (pressedKeyCode != KeyCode.None)
        {
            for (int i = 0; i < keyBindingData.keys.Length; i++)
            {
                if (keyBindingData.keys[i] == pressedKeyCode && (keyType != i))// ภฬนฬ ป็ฟ๋ ม฿ภฮ keyCodeธฆ ม๖มควั ฐๆฟ์
                {
                    // ผญทฮภว keyCodeธฆ บฏฐๆ
                    KeyCode tempKey = keyBindingData.keys[keyType];
                    //keyBindingData.keys[(int)keyType] = pressedKeyCode;
                    //keyBindingData.keys[i] = tempKey;
                    GameManager.Instance.KeyChanger((KeyType)keyType, pressedKeyCode);
                    GameManager.Instance.KeyChanger((KeyType)i, tempKey);
                    changeKeyName[keyType].text = pressedKeyCode.ToString();
                    changeKeyName[i].text = tempKey.ToString();
                    return;
                }
            }
            GameManager.Instance.KeyChanger((KeyType)keyType, pressedKeyCode); // ฝวมฆทฮ ลฐธฆ บฏฐๆวฯดย วิผ๖
            changeKeyName[keyType].text = pressedKeyCode.ToString();
            isClickKeyChanger[keyType] = false;

        }
    }

    public void ClickChangeKey(int i) // ลฐ บฏฐๆ น๖ฦฐภป ดฉธฆ ฝร ฝววเตวดย วิผ๖. 
    {
        for (int j = 0; j < isClickKeyChanger.Length; j++)
        {
            isClickKeyChanger[j] = false;
        }
        isClickKeyChanger[i] = true; // บฏฐๆวา ฐชฟก วุด็วฯดย keyภว ฐช ศฎภฮ
    }
}
