using UnityEngine;

/// <summary>
/// this = Player Object's Child Transform.
/// Weapons's parent = this.
/// if Scene Change ? PlayerManager.HasWeapons Update
/// 
/// ХЌЗЁНК КаИЎРЧЕЕ : PlayerManager ObjectРЧ АњЧб ПЌЛъ СйРЬБт.
/// </summary>

public class PlayerInventory : MonoBehaviour
{
    private PlayerManager PM;
    //public List<WeaponInstance> HasWeapons { get; private set; } = new List<WeaponInstance>();


    /// <summary>
    /// Scene НУРл НУ. PlayerManagerРЧ HasWeapon ЧвДч.
    /// </summary>
    private void OnEnable()
    {
        PM = PlayerManager.Instance;
    }


    /// <summary>
    /// Input РЛ ХыЧи ЙЋБт NumberРЛ ЙоОЦ, ЧіРч ЙЋБт ЛшСІ ШФ ЧиДч NumberРЧ ЙЋБт Л§МК.
    /// </summary>
    /// <param name="weapon"></param>
    public void ChangeWeapon(int weaponNum)
    {
        if (weaponNum < 0 || weaponNum > PM.MaxWeaponCount) return;

        WeaponInstance instance = PM.HasWeapons[weaponNum];
        if (instance == null) return;
        // РЬРќ weapon ЛшСІ
        WeaponBase[] beforeWeapons = GetComponentsInChildren<WeaponBase>();
        foreach (WeaponBase before in beforeWeapons) before.gameObject.SetActive(false);

        PM.SelectWeapon(instance.Id);
    }
}

